"""empty message

Revision ID: 0b3fc69a9d44
Revises: f0327357a564
Create Date: 2023-11-21 16:35:25.278970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3fc69a9d44'
down_revision: Union[str, None] = 'f0327357a564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklists', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'checklists', 'users', ['user_id'], ['user_id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checklists', type_='foreignkey')
    op.drop_column('checklists', 'user_id')
    # ### end Alembic commands ###
