"""empty message

Revision ID: 138b593e52de
Revises: d3120889b742
Create Date: 2023-11-18 03:12:30.314538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '138b593e52de'
down_revision: Union[str, None] = 'd3120889b742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_list_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('tasks_passage_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'task_lists', ['task_list_id'], ['id'])
    op.drop_column('tasks', 'passage_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('passage_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_passage_id_fkey', 'tasks', 'products', ['passage_id'], ['id'])
    op.drop_column('tasks', 'task_list_id')
    # ### end Alembic commands ###
