"""empty message

Revision ID: 22cebff1577f
Revises: 138b593e52de
Create Date: 2023-11-18 03:38:02.766926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22cebff1577f'
down_revision: Union[str, None] = '138b593e52de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passages')
    op.drop_constraint('tasks_parent_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('parent_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('tasks_parent_id_fkey', 'tasks', 'tasks', ['parent_id'], ['id'])
    op.create_table('passages',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='passages_device_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='passages_pkey'),
    sa.UniqueConstraint('id', name='passages_id_key')
    )
    # ### end Alembic commands ###
