"""empty message

Revision ID: 296c32987054
Revises: 49d2552bcc99
Create Date: 2023-11-18 01:24:30.931233

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '296c32987054'
down_revision: Union[str, None] = '49d2552bcc99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_lists',
                    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('product_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.drop_table('completed_tasks')
    op.create_unique_constraint(None, 'comments', ['id'])
    op.add_column('devices', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'devices', ['id'])
    op.drop_column('devices', 'model')
    op.drop_column('devices', 'os_version')
    op.drop_column('devices', 'os')
    op.create_unique_constraint(None, 'passages', ['id'])
    op.create_unique_constraint(None, 'products', ['id'])
    op.create_unique_constraint(None, 'reports', ['id'])
    op.create_unique_constraint(None, 'tasks', ['id'])
    op.drop_constraint('tasks_passage_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'products', ['passage_id'], ['id'])
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_passage_id_fkey', 'tasks', 'passages', ['passage_id'], ['id'])
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_constraint(None, 'reports', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'passages', type_='unique')
    op.add_column('devices', sa.Column('os', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('devices', sa.Column('os_version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('devices', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_column('devices', 'name')
    op.drop_constraint(None, 'comments', type_='unique')
    op.create_table('completed_tasks',
                    sa.Column('id', sa.BIGINT(),
                              sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807,
                                          cycle=False, cache=1), autoincrement=True, nullable=False),
                    sa.Column('parent_id', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('passage_id', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], name='completed_tasks_parent_id_fkey'),
                    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], name='completed_tasks_passage_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='completed_tasks_pkey'),
                    sa.UniqueConstraint('parent_id', name='completed_tasks_parent_id_key'),
                    sa.UniqueConstraint('passage_id', name='completed_tasks_passage_id_key')
                    )
    op.drop_table('task_lists')
    # ### end Alembic commands ###
