"""

Revision ID: 52618ac5212c
Revises: ab3e95d226bc
Create Date: 2024-10-13 00:24:52.078523

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52618ac5212c"
down_revision: Union[str, None] = "ab3e95d226bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "test_status",
            sa.Enum(
                "no_status",
                "passed",
                "failed",
                "impossible",
                "skipped",
                name="teststatus",
                native_enum=False,
            ),
            nullable=False,
        ),
    )
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Enum(
            "to_do",
            "in_progress",
            "done",
            name="taskstatus",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.Enum(
            "to_do",
            "in_progress",
            "done",
            name="taskstatus",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    op.drop_column("tasks", "test_status")
    # ### end Alembic commands ###
