"""empty message

Revision ID: 681a9cc2e24c
Revises: 296c32987054
Create Date: 2023-11-18 01:33:40.845081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '681a9cc2e24c'
down_revision: Union[str, None] = '296c32987054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('devices_user_id_fkey', 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'users', ['user_id'], ['user_id'])
    op.create_unique_constraint(None, 'task_lists', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_lists', type_='unique')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key('devices_user_id_fkey', 'devices', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
