"""empty message

Revision ID: aee5da40d38f
Revises: 99c95eb31453
Create Date: 2023-11-21 16:32:41.211014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee5da40d38f'
down_revision: Union[str, None] = '99c95eb31453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'checklists', ['id'])
    op.drop_constraint('checklists_product_id_fkey', 'checklists', type_='foreignkey')
    op.create_foreign_key(None, 'checklists', 'products', ['product_id'], ['id'], ondelete='cascade')
    op.create_unique_constraint(None, 'comments', ['id'])
    op.create_unique_constraint(None, 'devices', ['id'])
    op.create_unique_constraint(None, 'products', ['id'])
    op.drop_constraint('products_owner_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['owner_id'], ['user_id'], ondelete='cascade')
    op.create_unique_constraint(None, 'reports', ['id'])
    op.drop_constraint('reports_task_id_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'tasks', ['task_id'], ['id'], ondelete='cascade')
    op.create_unique_constraint(None, 'tasks', ['id'])
    op.drop_constraint('tasks_user_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_checklist_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'checklists', ['checklist_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['user_id'], ondelete='cascade')
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_checklist_id_fkey', 'tasks', 'checklists', ['checklist_id'], ['id'])
    op.create_foreign_key('tasks_user_id_fkey', 'tasks', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_task_id_fkey', 'reports', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'reports', type_='unique')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_owner_id_fkey', 'products', 'users', ['owner_id'], ['user_id'])
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_constraint(None, 'comments', type_='unique')
    op.drop_constraint(None, 'checklists', type_='foreignkey')
    op.create_foreign_key('checklists_product_id_fkey', 'checklists', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'checklists', type_='unique')
    # ### end Alembic commands ###
