"""empty message

Revision ID: d3120889b742
Revises: 681a9cc2e24c
Create Date: 2023-11-18 01:38:33.261201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3120889b742'
down_revision: Union[str, None] = '681a9cc2e24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_task_id_key', 'comments', type_='unique')
    op.drop_constraint('devices_user_id_key', 'devices', type_='unique')
    op.drop_constraint('passages_device_id_key', 'passages', type_='unique')
    op.drop_constraint('reports_task_id_key', 'reports', type_='unique')
    op.drop_constraint('tasks_parent_id_key', 'tasks', type_='unique')
    op.drop_constraint('tasks_passage_id_key', 'tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tasks_passage_id_key', 'tasks', ['passage_id'])
    op.create_unique_constraint('tasks_parent_id_key', 'tasks', ['parent_id'])
    op.create_unique_constraint('reports_task_id_key', 'reports', ['task_id'])
    op.create_unique_constraint('passages_device_id_key', 'passages', ['device_id'])
    op.create_unique_constraint('devices_user_id_key', 'devices', ['user_id'])
    op.create_unique_constraint('comments_task_id_key', 'comments', ['task_id'])
    # ### end Alembic commands ###
